### ISSUE TITLE
Bundling error

### ISSUE THREAD

**Issue by phoeniceus** [jspm/jspm.io#51]
I have an application that uses jspm/systemjs and runs fine in my browser transpiling on the fly. But when I try to bundle the application, I get the same error, no matter how I call bundle/build (running jspm 0.17.0-beta.25):

> D:\Work\TMobile\B2B\trunk\B2B\B2B>jspm bundle ./src/app.js ./src/bundle.js
>      Building the bundle tree for ./src/app.js...

err  Error: Error compiling amd module "github:Leaflet/Leaflet@1.0.0-rc.2/dist/leaflet-src.js" at jspm_packages\github\Leaflet\Leaflet@1.0.0-rc.2\dist\leaflet-src.js
  SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. Both were omitted.
    at SourceMapGenerator_applySourceMap [as applySourceMap](D:WorkTMobileB2BtrunkB2BB2Bnode_modulestraceurbintraceur.js:26375:17)
    at Compiler.getSourceMap (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\traceur\bin\traceur.js:31879:23)
    at Object.exports.compile (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\systemjs-builder\compilers\amd.js:386:25)
    at D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\systemjs-builder\lib\compile.js:117:43
    at tryCatcher (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromiseCtx (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\promise.js:598:10)
    at Async._drainQueue (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\async.js:143:12)
    at Async._drainQueues (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (D:\Work\TMobile\B2B\trunk\B2B\B2B\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)

I don't know what the problem is, but I noted that the stack trace above accesses traceur.js. I find this odd, because I am using babel, not traceur. I've attached the config files so you can see how babel is referenced.

[jspm.config.js.txt](https://github.com/jspm/jspm.io/files/404406/jspm.config.js.txt)
[package.json.txt](https://github.com/jspm/jspm.io/files/404407/package.json.txt)

**Comment by guybedford** [comment]
Traceur is still used internally even though the main transpiler is Babel.

There is work going on to move the internal compilation entirely to Babel which should address this issue I think. This is tracking in https://github.com/systemjs/builder/issues/489.
